spring.application.name=SpringOAuthDemo

spring.security.oauth2.client.registration.google.client-id=type_your_key
spring.security.oauth2.client.registration.google.client-secret=type_your_key


spring.security.oauth2.client.registration.github.client-id=type_your_key
spring.security.oauth2.client.registration.github.client-secret=type_your_key